'use client';

import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';

type Session={id:string;title:string;status:string;starts_at:string|null;pinned_listing_id:string|null;featured_listing_ids:string[]|null;live_room_name:string|null};
type Listing={id:string;title:string;description:string|null;listing_type:string;currency:string;price:number|null;compare_at_price:number|null;quantity_available:number|null;media:any};
type Auction={listing_id:string;starts_at:string|null;ends_at:string|null;starting_bid:number|null;reserve_price:number|null;buy_now_price:number|null;bid_increment:number|null;anti_sniping_seconds:number|null;status:string;current_bid:number|null};

function Countdown({target}:{target:string|null}){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);if(!target)return <span>Live timing pending</span>;const delta=Math.max(0,new Date(target).getTime()-now);const s=Math.floor(delta/1000);const h=Math.floor(s/3600);const m=Math.floor((s%3600)/60);const sec=s%60;return <span aria-live="polite">{delta<=0?'ENDED':`${h}h ${m}m ${sec}s`}</span>}

export default function LiveShoppingPage(){
 const [sessions,setSessions]=useState<Session[]>([]),[listings,setListings]=useState<Listing[]>([]),[auctions,setAuctions]=useState<Auction[]>([]),[message,setMessage]=useState('Loading live shopping…');
 useEffect(()=>{fetch('/api/live-shopping').then(async r=>({r,d:await r.json()})).then(({r,d})=>{if(!r.ok){setMessage(d.error??'Live shopping unavailable.');return;}setSessions(d.sessions??[]);setListings(d.listings??[]);setAuctions(d.auctions??[]);setMessage('');}).catch(()=>setMessage('Live shopping unavailable.'))},[]);
 const listingMap=useMemo(()=>new Map(listings.map(l=>[l.id,l])),[listings]);
 return <main className="product-shell"><header className="product-header"><Link href="/" className="brand-link">TRYAMM</Link><nav className="product-nav"><Link href="/marketplace">Marketplace</Link><Link href="/live">LIVE/PK</Link><Link href="/checkout">Checkout</Link><Link href="/wallet">Wallet</Link></nav></header><section className="product-hero"><p className="eyebrow">LIVE SHOPPING • COUNTDOWN DEALS • AUCTIONS • CALL-IN</p><h1>TRYAMM Live Shopping</h1><p className="lede">A QVC/HSN-style shopping channel fused with TRYAMM LIVE, creator commerce, auctions, limited-time drops and Middleverse call-in support.</p></section><section className="world-grid"><p role="status">{message}</p><div className="cards">{sessions.map(s=>{const pinned=s.pinned_listing_id?listingMap.get(s.pinned_listing_id):undefined;return <article key={s.id}><p className="eyebrow">{s.status.toUpperCase()}</p><h2>{s.title}</h2>{s.starts_at&&<p>Starts: {new Date(s.starts_at).toLocaleString()}</p>}{pinned&&<><h3>Pinned: {pinned.title}</h3><p>{pinned.description}</p><strong>{pinned.price!=null?new Intl.NumberFormat(undefined,{style:'currency',currency:pinned.currency||'USD'}).format(Number(pinned.price)):'Price on show'}</strong><p>Qty: {pinned.quantity_available??'—'}</p><Link className="button-link" href={`/checkout?product=${pinned.id}`}>Buy pinned item →</Link></>}<div className="actions"><Link className="button-link secondary" href="/live">Watch LIVE</Link><Link className="button-link secondary" href="/middleverse">Call in</Link></div></article>})}</div><h2>Countdown Auctions</h2><div className="cards">{auctions.map(a=>{const l=listingMap.get(a.listing_id);return <article key={a.listing_id}><p className="eyebrow">{a.status.toUpperCase()}</p><h3>{l?.title??'Auction item'}</h3><p>Current bid: {a.current_bid!=null?new Intl.NumberFormat(undefined,{style:'currency',currency:l?.currency??'USD'}).format(a.current_bid):'No bids yet'}</p><p>Starting bid: {a.starting_bid??'—'} • Increment: {a.bid_increment??'—'}</p>{a.buy_now_price!=null&&<p>Buy now: {a.buy_now_price}</p>}<p>Time remaining: <Countdown target={a.ends_at}/></p><p className="muted">Anti-sniping: {a.anti_sniping_seconds??0}s</p><button disabled title="Bidding API is server-validated before launch">Place bid</button></article>})}</div></section></main>;
}
