import type { LegacyDesignRecord } from "./types";
import { recoveredTryammSpacecraft } from "./recovered-spacecraft";

const sharedSafety = [
  "Unknown legacy claims must remain unresolved until supported by source evidence.",
  "Physical products require independent engineering validation before real-world use.",
  "AI planning does not authorize physical actuation or regulated operation.",
];

export const recoveredLegacyDesigns: LegacyDesignRecord[] = [
  recoveredTryammSpacecraft,
  {
    id: "legacy-silver-hawk-001",
    name: "Silver Hawk Flying Car",
    domain: "flying_car",
    aliases: ["Silver Hawk", "TRYAMM flying car"],
    summary: "Recovered flying-car/electric mobility concept intended to connect TRYAMM MobilityOS with advanced electric propulsion, autonomous assistance and accessible transportation workflows.",
    recoveredFacts: [
      "Silver Hawk was previously identified as a flying-car concept.",
      "The broader mobility architecture includes electric vehicles, eVTOL/flying-vehicle dispatch, accessibility-aware routing and shared Stubbs AI orchestration.",
    ],
    unresolvedSpecs: ["validated propulsion architecture", "airframe geometry", "range", "speed", "battery chemistry", "certification basis", "physical BOM"],
    dependencies: ["MobilityOS", "Stubbs AI", "Googolplex Memory", "Guardian", "digital twin", "ManufacturingOS"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "partial",
    implementationStatus: "concept",
  },
  {
    id: "legacy-aircraft-001",
    name: "TRYAMM Aircraft Platform",
    domain: "aircraft",
    aliases: ["TRYAMM plane", "El Saturn aircraft"],
    summary: "Recovered aircraft platform concept for AI-assisted planning, simulation, navigation, accessible passenger workflows and future certified deterministic flight-control integration.",
    recoveredFacts: ["Aircraft/plane concepts were part of the prior mobility discussion.", "MobilityOS now provides shared fleet, mission, energy and safety abstractions."],
    unresolvedSpecs: ["aircraft configuration", "propulsion", "capacity", "flight envelope", "materials", "avionics", "certification program"],
    dependencies: ["MobilityOS", "digital twin", "weather gate", "airspace manager", "ManufacturingOS"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "reference_only",
    implementationStatus: "concept",
  },
  {
    id: "legacy-marine-001",
    name: "TRYAMM Marine Platform",
    domain: "marine",
    aliases: ["TRYAMM boat", "electric boat", "autonomous marine craft"],
    summary: "Recovered marine mobility concept covering electric boats, cargo/passenger vessels and supervised autonomous marine missions under MobilityOS.",
    recoveredFacts: ["Boat/marine concepts were previously discussed.", "MobilityOS recognizes marine vehicles as a supported class."],
    unresolvedSpecs: ["hull geometry", "propulsion", "battery/fuel system", "capacity", "navigation hardware", "marine certification/inspection basis"],
    dependencies: ["MobilityOS", "marine navigation adapter", "weather/water-state gate", "ManufacturingOS"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "reference_only",
    implementationStatus: "concept",
  },
  {
    id: "legacy-drone-001",
    name: "TRYAMM Drone Systems",
    domain: "drone",
    aliases: ["delivery drone", "Phantom Twist", "invisible drone concept"],
    summary: "Recovered drone family for delivery, inspection, mapping and logistics handoff, integrated with MobilityOS safety envelopes and mission audit.",
    recoveredFacts: ["Drone delivery and advanced drone concepts were previously requested.", "MobilityOS now provides drone mission, payload, battery, geofence and operator gates."],
    unresolvedSpecs: ["specific airframe", "propulsion", "sensor suite", "payload envelope", "validated autonomy level"],
    dependencies: ["MobilityOS", "Universal Mission Handoff", "Guardian", "airspace/geofence service"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "partial",
    implementationStatus: "partial",
  },
  {
    id: "legacy-ev-001",
    name: "TRYAMM Electric Vehicle Platform",
    domain: "ground_vehicle",
    aliases: ["TRYAMM EV", "HoloRide EV", "electric Formula/NASCAR derivative"],
    summary: "Recovered electric-vehicle family spanning accessible rideshare, fleet charging, high-performance concepts and shared MobilityOS dispatch.",
    recoveredFacts: ["Electric vehicle and electric racing-car concepts were previously developed at architecture/design level.", "MobilityOS now provides energy-aware dispatch and accessible mission planning."],
    unresolvedSpecs: ["final production chassis", "validated motor/inverter/battery stack", "crashworthiness", "homologation/certification", "manufacturing BOM"],
    dependencies: ["MobilityOS", "Energy Manager", "ManufacturingOS", "accessible dispatch"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "partial",
    implementationStatus: "partial",
  },
  {
    id: "legacy-robotics-001",
    name: "Stubbs Robotics OS",
    domain: "robotics",
    aliases: ["TRYAMM robotics", "robot fleet"],
    summary: "Recovered robotics architecture for registry, world models, sensor fusion, deterministic motion, fleet coordination, accessibility and emergency-stop safety.",
    recoveredFacts: ["Robotics was specified as a first-class TRYAMM physical-action domain.", "The architecture separates AI planning from deterministic actuator control."],
    unresolvedSpecs: ["specific robot hardware families", "motor/controller interfaces", "certification requirements by use case"],
    dependencies: ["Stubbs AI", "Five-Senses", "Guardian", "MobilityOS", "digital twin"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "partial",
    implementationStatus: "partial",
  },
  {
    id: "legacy-spaceos-001",
    name: "SpaceOS",
    domain: "spaceos",
    aliases: ["TRYAMM SpaceOS", "El Saturn SpaceOS"],
    summary: "Recovered SpaceOS digital-twin and manufacturing workflow for immersive physical-world modeling, room/object scanning, CAD outputs, planetary mission systems and safety-gated BUILD.",
    recoveredFacts: ["Persistent digital twins are part of the locked SpaceOS baseline.", "The baseline includes 3D editing, vision analysis, authenticated private data, BUILD jobs and STL/STEP output."],
    unresolvedSpecs: ["complete production deployment", "full CAD/manufacturing back end", "all physical safety validators"],
    dependencies: ["Stubbs AI", "Googolplex Memory", "Supabase", "ManufacturingOS"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "partial",
    implementationStatus: "partial",
  },
  {
    id: "legacy-12d-001",
    name: "TRYAMM 12D Manufacturing",
    domain: "manufacturing_12d",
    aliases: ["12D printer", "12D manufacturing", "HoloForge manufacturing"],
    summary: "Recovered advanced manufacturing concept intended to transform verified digital twins and CAD/STEP/STL/BOM artifacts into safety-gated manufacturing jobs.",
    recoveredFacts: ["12D-printing/manufacturing was part of the broader TRYAMM hardware/manufacturing vision.", "Manufacturing must remain gated by CAD/STEP/BOM/material/process and engineering verification."],
    unresolvedSpecs: ["formal definition of 12D process", "machine architecture", "supported materials", "process physics", "certified tolerances", "production hardware"],
    dependencies: ["SpaceOS", "ManufacturingOS", "digital twin", "engineering verification"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "reference_only",
    implementationStatus: "concept",
  },
  {
    id: "legacy-energy-001",
    name: "TRYAMM Advanced Energy Systems",
    domain: "energy",
    aliases: ["Blue Energy", "living water energy", "solid-state battery program"],
    summary: "Recovered energy-system family associated with mobility and hardware concepts, including advanced battery and ambient-energy ideas that require independent scientific validation.",
    recoveredFacts: ["Blue Energy, solid-state battery and related energy concepts were previously discussed as future R&D directions."],
    unresolvedSpecs: ["validated energy source", "measured output", "efficiency", "safety", "materials", "independent reproducibility"],
    dependencies: ["Benchmark & Proof Engine", "ManufacturingOS", "independent lab validation"],
    safetyRequirements: [...sharedSafety, "Energy-performance claims require reproducible measurements before being represented as proven."],
    artifacts: [],
    recoveryConfidence: "reference_only",
    implementationStatus: "concept",
  },
  {
    id: "legacy-holographic-hardware-001",
    name: "TRYAMM Holographic Hardware Family",
    domain: "robotics",
    aliases: ["HoloCube", "HoloTV", "holographic sound bar", "holographic phone/tablet/TV clip"],
    summary: "Recovered holographic-display and spatial-interface hardware family intended to extend TRYAMM experiences beyond standard screens.",
    recoveredFacts: ["HoloCube, HoloTV, holographic sound bar and display/casting concepts were previously part of the hardware roadmap."],
    unresolvedSpecs: ["optical architecture", "display technology", "manufacturing design", "thermal/power design", "production BOM"],
    dependencies: ["Stubbs AI", "HoloGPT UI", "ManufacturingOS", "accessibility contract"],
    safetyRequirements: sharedSafety,
    artifacts: [],
    recoveryConfidence: "partial",
    implementationStatus: "concept",
  },
];

export function getLegacyDesign(idOrAlias: string): LegacyDesignRecord | undefined {
  const normalized = idOrAlias.trim().toLowerCase();
  return recoveredLegacyDesigns.find(
    (design) => design.id.toLowerCase() === normalized || design.name.toLowerCase() === normalized || design.aliases.some((alias) => alias.toLowerCase() === normalized),
  );
}
